### ISSUE TITLE
Move cron job out of cloudinit

### ISSUE THREAD

**Issue by felddy** [cisagov/freeipa-server-tf-module#13]
> It'd be nice if this wasn't in cloudinit so we could get some shell-check love.
> 
> The script would need to get the `domain` variable at runtime. This would also make it tolerant to domain changes. (which will probably never happen)
> 
> I couldn't find a k-command to spit out the realms, but something like this maybe?:
> 
> ```
> [mark.feldhousen@ipa ~]$ grep "default_realm" /etc/krb5.conf | awk '{print $3}'
> COOL.CYBER.DHS.GOV
> ```
> 
> With that change it could be installed back in ansible land.

I am out of time now, but I will look into determining the domain at runtime when I have a chance.

_Originally posted by @jsf9k in https://github.com/cisagov/freeipa-master-tf-module/pull/12#issuecomment-538002251_

**Comment by dav3r** [comment]
@jsf9k, @felddy - I don't think this issue is relevant anymore.  Can it be closed out?

**Comment by jsf9k** [comment]
The cron job now lives in [cisagov/ansible-role-freeipa-server](https://github.com/cisagov/ansible-role-freeipa-server).

**Comment by dav3r** [comment]
Issue moved to [cisagov/ansible-role-freeipa-server #9](https://github.com/cisagov/ansible-role-freeipa-server/issues/9) via [**ZenHub**](https://www.zenhub.com/)
